baseURL: "https://nimahomepage.netlify.app/"
languageCode: "en-us"
title: "Nima T. Bazargani"
theme: "PaperMod"

publishDir: "public"

# IMPORTANT: allow raw HTML in markdown (for your <div class="make_bg ..."> blocks)
markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      typographer: false

mathEngine: "katex"

# Optional: make Hugo use absolute URLs based on baseURL
canonifyURLs: true

params:
  env: production

  # Theme + appearance
  defaultTheme: dark        # <- force dark
  disableThemeToggle: true
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowShareButtons: false
  ShowCodeCopyButtons: true
  disableScrollToTop: false

  # Tell PaperMod to load your custom CSS from /assets
  assets:
    customCSS:
      - css/extended/blank.css   # corresponds to assets/css/extended/blank.css

  math: true

  profileMode:
    enabled: false

  homeInfoParams:
    Title: ""
    Content: ""

menu:
  main:
    - name: about
      url: /about/
      weight: 1

    - name: research
      url: /research/
      weight: 2

    - name: projects
      url: /projects/
      weight: 3

    - name: blog
      url: /posts/
      weight: 4

    - name: cv
      url: /cv/
      weight: 5

    - name: contact
      url: /contact/
      weight: 6
